spring.application.name=project
server.port=8090

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.frzlamnvmazbwftrlpkw
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=app
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG